### ISSUE TITLE
Baby boo

### ISSUE THREAD

**Issue by chukwunonsoikenwa** [Frances-Odunaiya/Frances-Odunaiya#1]
Hi baby

**Comment by chukwunonsoikenwa** [comment]
What do you think about us

**Comment by chukwunonsoikenwa** [comment]
You didn't pick up my call yesterday

**Comment by Frances-Odunaiya** [comment]
You don't have sense

> You didn't pick up my call yesterday

**Comment by Frances-Odunaiya** [comment]
Issues fixed!

**Comment by Frances-Odunaiya** [comment]
> Hi baby

what do you mean?

**Comment by Frances-Odunaiya** [comment]
> You didn't pick up my call yesterday

seen it now?
